CREATE TABLE klienci (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dane_osobowe TEXT,
    adres TEXT,
    produkty TEXT
);

INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Wiśniewski', 'ul. Parkowa ,   Tychy', 'Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Szymański', 'ul. Długa ,', 'Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Grabowska', 'ul. Lipowa 44,  Lublin', 'Monitor, Kamera internetowa, Mysz, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Nowak', 'ul. Orla 50, 30-400 Warszawa', 'Laptop, Słuchawki, Router, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Wieczorek', 'ul. Różana 23,  Kraków', 'Mysz, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Kubiak', 'ul. Słoneczna  , 80-001', 'Tablet, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Nowak', 'ul. Lipowa  ,  Kraków', 'Monitor, Laptop, Mysz, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Kubiak', 'ul. Długa  ,', 'Mysz, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Agnieszka Wójcik', 'ul. Mickiewicza ,', 'Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Zając', 'ul. Szkolna  , 43-100 Szczecin', 'Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Pawlak', 'ul. Mickiewicza  , 70-100', 'Drukarka, Monitor, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Wieczorek', 'ul. Szkolna , 70-100 Kraków', 'Drukarka, Słuchawki, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Zając', 'ul. Lipowa  ,   Szczecin', 'Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Wieczorek', 'ul. Szkolna ,   Szczecin', 'Słuchawki, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Wójcik', 'ul. Spacerowa 28,', 'Mysz, Drukarka, Laptop, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Nowak', 'ul. Spacerowa ,', 'Router, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Kowalski', 'ul. Parkowa 20,', 'Słuchawki, Klawiatura, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Kubiak', 'ul. Orla  , 90-001 Szczecin', 'Telefon, Laptop, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Grabowska', 'ul. Lipowa  , 00-001 Poznań', 'Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Baran', 'ul. Długa ,', 'Kamera internetowa, Słuchawki, Klawiatura, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Agnieszka Szymański', 'ul. Lipowa 6,   Rzeszów', 'Router, Kamera internetowa, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Kowalski', 'ul. Lipowa  , 60-100', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Zając', 'ul. Długa ,', 'Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Maj', 'ul. Różana , 60-100 Gdańsk', 'Klawiatura, Kamera internetowa, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Baran', 'ul. Lipowa 49, 20-001', 'Router, Telefon, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Agnieszka Wójcik', 'ul. Różana  ,', 'Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Malinowski', 'ul. Spacerowa ,   Kraków', 'Klawiatura, Telefon, Monitor, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Jan Czerwińska', 'ul. Spacerowa ,', 'Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Lis', 'ul. Orla  ,', 'Laptop, Telefon, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Walczak', 'ul. Polna  ,', 'Router, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Lis', 'ul. Mickiewicza , 80-001', 'Mysz, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Król', 'ul. Parkowa  ,', 'Tablet, Laptop, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Kamil Malinowski', 'ul. Spacerowa 2,  Warszawa', 'Monitor, Telefon, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Lewandowska', 'ul. Różana 44, 30-400', 'Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Lewandowska', 'ul. Różana ,', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Król', 'ul. Spacerowa ,', 'Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Malinowski', 'ul. Słoneczna  , 35-100', 'Laptop, Router, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Wiśniewski', 'ul. Długa 12,   Katowice', 'Telefon, Kamera internetowa, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Pawlak', 'ul. Długa  , 80-001 Poznań', 'Monitor, Drukarka, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Wiśniewski', 'ul. Orla , 20-001', 'Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Jan Kowalski', 'ul. Różana , 43-100', 'Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Maj', 'ul. Słoneczna 8,  Lublin', 'Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Czerwińska', 'ul. Orla  ,   Gdańsk', 'Kamera internetowa, Mysz, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Maj', 'ul. Szkolna  ,  Tychy', 'Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Grabowska', 'ul. Polna ,', 'Klawiatura, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Jan Maj', 'ul. Orla ,  Rzeszów', 'Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Malinowski', 'ul. Orla ,  Gdańsk', 'Telefon, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Kamińska', 'ul. Słoneczna 17, 90-001 Rzeszów', 'Mysz, Kamera internetowa, Router, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Baran', 'ul. Szkolna  ,  Kraków', 'Drukarka, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Krawczyk', 'ul. Słoneczna , 35-100 Warszawa', 'Kamera internetowa, Klawiatura, Tablet, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Krawczyk', 'ul. Orla 44,', 'Monitor, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Król', 'ul. Mickiewicza 24,  Warszawa', 'Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Grabowska', 'ul. Mickiewicza 5, 90-001', 'Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Czerwińska', 'ul. Polna  ,', 'Drukarka, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Maj', 'ul. Słoneczna  , 90-001', 'Mysz, Tablet, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Nowak', 'ul. Słoneczna 20,', 'Tablet, Telefon, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Nowak', 'ul. Parkowa ,', 'Mysz, Klawiatura, Router, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Lis', 'ul. Parkowa  , 60-100', 'Drukarka, Kamera internetowa, Telefon, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Nowak', 'ul. Orla , 90-001 Kraków', 'Laptop, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Szymański', 'ul. Długa  , 00-001', 'Klawiatura, Monitor, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Wiśniewski', 'ul. Szkolna  ,', 'Telefon, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Zając', 'ul. Spacerowa 11, 20-001', 'Słuchawki, Laptop, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Olga Zając', 'ul. Lipowa 9,', 'Drukarka, Klawiatura, Telefon, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Lewandowska', 'ul. Szkolna ,', 'Tablet, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Pawlak', 'ul. Szkolna  ,', 'Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Baran', 'ul. Polna ,', 'Tablet, Słuchawki, Mysz, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Nowak', 'ul. Spacerowa , 20-001', 'Mysz, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Baran', 'ul. Długa 49, 35-100', 'Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Grabowska', 'ul. Słoneczna ,', 'Tablet, Drukarka, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Wójcik', 'ul. Parkowa  , 00-001 Lublin', 'Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Malinowski', 'ul. Słoneczna  , 40-001 Warszawa', 'Drukarka, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Malinowski', 'ul. Długa 3, 43-100', 'Monitor, Mysz, Klawiatura, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Nowak', 'ul. Orla  ,  Rzeszów', 'Tablet, Słuchawki, Monitor, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Nowak', 'ul. Orla , 70-100 Poznań', 'Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Kamińska', 'ul. Mickiewicza 14,', 'Klawiatura, Telefon, Router, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Szymański', 'ul. Słoneczna ,  Tychy', 'Router, Telefon, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Kamińska', 'ul. Lipowa 2, 43-100 Szczecin', 'Klawiatura, Słuchawki, Kamera internetowa, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Wieczorek', 'ul. Różana ,', 'Monitor, Słuchawki, Klawiatura, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Malinowski', 'ul. Długa ,', 'Słuchawki, Drukarka, Laptop, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Baran', 'ul. Parkowa , 40-001', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Kamińska', 'ul. Lipowa 20,', 'Telefon, Słuchawki, Drukarka, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Król', 'ul. Polna , 30-400 Szczecin', 'Laptop, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Kowalski', 'ul. Polna 12,   Szczecin', 'Kamera internetowa, Mysz, Klawiatura, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Kubiak', 'ul. Długa 22, 30-400 Tychy', 'Drukarka, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Zając', 'ul. Szkolna  ,  Kraków', 'Monitor, Klawiatura, Router, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Pawlak', 'ul. Lipowa  , 60-100', 'Router, Tablet, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Walczak', 'ul. Orla ,  Poznań', 'Kamera internetowa, Monitor, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Krawczyk', 'ul. Słoneczna ,', 'Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Szymański', 'ul. Mickiewicza  , 43-100 Rzeszów', 'Laptop, Klawiatura, Drukarka, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Kamil Kamińska', 'ul. Polna  ,', 'Kamera internetowa, Słuchawki, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Lis', 'ul. Słoneczna ,', 'Laptop, Monitor, Mysz, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Czerwińska', 'ul. Spacerowa  ,  Rzeszów', 'Kamera internetowa, Telefon, Słuchawki, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Jan Lis', 'ul. Mickiewicza 42,', 'Kamera internetowa, Drukarka, Monitor, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Szymański', 'ul. Spacerowa , 35-100 Poznań', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Baran', 'ul. Lipowa , 20-001', 'Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Grabowska', 'ul. Różana ,', 'Drukarka, Mysz, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Maj', 'ul. Spacerowa  ,', 'Mysz, Kamera internetowa, Drukarka, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Nowak', 'ul. Polna  ,', 'Słuchawki, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Wiśniewski', 'ul. Różana ,   Łódź', 'Router, Laptop, Mysz, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Agnieszka Wójcik', 'ul. Parkowa ,  Tychy', 'Laptop, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Lis', 'ul. Różana , 00-001', 'Drukarka, Monitor, Router, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Malinowski', 'ul. Mickiewicza 39, 35-100', 'Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Agnieszka Wiśniewski', 'ul. Długa 25,  Kraków', 'Klawiatura, Router, Laptop, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Wieczorek', 'ul. Spacerowa 43, 30-400', 'Mysz, Słuchawki, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Wójcik', 'ul. Spacerowa 14, 60-100', 'Telefon, Monitor, Tablet, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Szymański', 'ul. Polna , 35-100 Poznań', 'Router, Drukarka, Tablet, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Wieczorek', 'ul. Spacerowa  ,', 'Słuchawki, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Kubiak', 'ul. Polna ,', 'Klawiatura, Kamera internetowa, Telefon, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Wójcik', 'ul. Szkolna 22,   Kraków', 'Telefon, Router, Słuchawki, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Agnieszka Kowalski', 'ul. Mickiewicza  ,', 'Klawiatura, Laptop, Monitor, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Walczak', 'ul. Różana , 00-001 Katowice', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Czerwińska', 'ul. Długa  ,   Lublin', 'Tablet, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Zając', 'ul. Szkolna  ,  Poznań', 'Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Grabowska', 'ul. Szkolna  ,', 'Drukarka, Tablet, Słuchawki, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Kowalski', 'ul. Parkowa  ,', 'Słuchawki, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Wieczorek', 'ul. Parkowa  ,', 'Klawiatura, Tablet, Telefon, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Zając', 'ul. Długa ,', 'Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Baran', 'ul. Szkolna  ,', 'Mysz, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Kowalski', 'ul. Lipowa  , 20-001 Katowice', 'Laptop, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Pawlak', 'ul. Różana  , 20-001', 'Mysz, Słuchawki, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Krawczyk', 'ul. Szkolna  ,   Warszawa', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Kamińska', 'ul. Szkolna , 80-001', 'Telefon, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Pawlak', 'ul. Długa  ,', 'Mysz, Monitor, Drukarka');
